import Navbar from "./component/Navbar";
import Hydrate from "./component/Hydrate";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { Poppins } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className={poppins.className}>
      <body className="lg:mx-24 mx-4">
        <Hydrate>
          <Navbar user={session?.user} />
          {children}
        </Hydrate>
      </body>
    </html>
  );
}
